### ISSUE TITLE
Do we have a chance to change the category slug url?

### ISSUE THREAD

**Issue by kuaza61** [v17development/flarum-blog#140]
Do we have a chance to change the category slug url?

example default url:
site.com/blog/**category**/general

Can we change it this way? :
site.com/blog/**kategori**/general

thanks

**Comment by iamdarkle** [comment]
Maybe the @clarkwinkelmann [Custom Paths](https://extiverse.com/extension/kilowhat/flarum-ext-custom-paths) extension could support this, I don't know if it does now or not.

**Comment by clarkwinkelmann** [comment]
Yes, my custom paths extension has support for the blog extension. It's not visible in the screenshot in my documentation because the screenshot is older, but the documentation lists the extension as compatible.

This is how the settings look like:
![image](https://user-images.githubusercontent.com/5264300/173245962-d8f10cf7-54cd-41de-8435-175fb4a7033f.png)

I'm not a regular user of the Blog extension though, so there's always a risk a change in the extension breaks compatibility. But if that's the case please let me know and I'll fix it ASAP.

**Comment by jaspervriends** [comment]
Cool! Then I'll close this issue 😎
