### ISSUE TITLE
To support bookmark an article 

### ISSUE THREAD

**Issue by alligatorrrr** [v17development/flarum-blog#145]
It will be nice If blog article can also support discussion bookmark ( by Clark) to allow user bookmark the article they like. So they can easily review them

**Comment by ctml91** [comment]
> It will be nice If blog article can also support discussion bookmark ( by Clark) to allow user bookmark the article they like. So they can easily review them

I could be wrong but you might need to ask the author of the other bookmark extension to support bookmarking blog posts. You will need to sponsor the feature as he doesn't work for free.

**Comment by iamdarkle** [comment]
I've posted an issue here (https://github.com/clarkwinkelmann/flarum-ext-bookmarks/issues/2) let's see what he thinks.

**Comment by clarkwinkelmann** [comment]
I have added the button to `flarum.core.compat['v17development/blog/pages/BlogItem'].prototype.contentItems` via my extension. 

That's how it looks for regular users:

![image](https://user-images.githubusercontent.com/5264300/178171827-e5a3fb23-e2f3-4198-ba8b-cfeb0a108a34.png)

As a development suggestion, it could be interesting to make the "edit"/"controls" area extensible horizontally so that admins can see the two buttons on the same line. Right now I have no choice but to add my button above or below the existing control:

![image](https://user-images.githubusercontent.com/5264300/178172009-39024911-cadc-49f9-b0c8-0a67ca5abde8.png)
